name: lsm
channels:
  - jmcmurray
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - anyio=3.5.0=py38haa244fe_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py38h294d835_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=21.12b0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blosc=1.21.0=h0e60522_0
  - boost-cpp=1.74.0=h5b4e17d_5
  - bottleneck=1.3.2=py38h6f4d8f0_5
  - brotlipy=0.7.0=py38h294d835_1003
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2020.10.14=0
  - cairo=1.16.0=h15b3021_1009
  - certifi=2020.6.20=py38_0
  - cffi=1.15.0=py38hd8c33c5_0
  - cfitsio=4.0.0=hd67004f_0
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=8.0.3=py38haa244fe_1
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=36.0.0=py38h21b164f_0
  - curl=7.81.0=h789b8ee_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py38h885f38d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - executing=0.8.2=pyhd8ed1ab_0
  - expat=2.4.3=h39d44d4_0
  - fiona=1.8.20=py38h19672d5_4
  - flit-core=3.6.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h1989441_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h546665d_1
  - freexl=1.0.6=ha8e266a_0
  - gdal=3.4.1=py38h67fab55_2
  - geos=3.10.2=h39d44d4_0
  - geotiff=1.7.0=h144821f_6
  - gettext=0.19.8.1=ha2e2712_1008
  - hdf4=4.2.15=h0e5069d_3
  - hdf5=1.12.1=nompi_h57737ce_103
  - icu=69.1=h0e60522_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.10.1=py38haa244fe_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=8.0.1=py38haa244fe_0
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.1=py38haa244fe_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter_client=7.1.1=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38haa244fe_1
  - jupyter_server=1.13.3=pyhd8ed1ab_0
  - jupyterlab=3.2.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - kealib=1.4.14=h8995ca9_3
  - krb5=1.19.2=h6da9e4a_3
  - lcms2=2.12=h2a16943_0
  - lerc=3.0=h0e60522_0
  - libblas=3.9.0=12_win64_mkl
  - libcblas=3.9.0=12_win64_mkl
  - libcurl=7.81.0=h789b8ee_0
  - libdeflate=1.8=h8ffe710_0
  - libffi=3.4.2=h8ffe710_5
  - libgdal=3.4.1=ha841e0a_2
  - libglib=2.70.2=h3be07f2_1
  - libiconv=1.16=he774522_0
  - libkml=1.3.0=h9859afa_1014
  - liblapack=3.9.0=12_win64_mkl
  - libnetcdf=4.8.1=nompi_h1cc8e9d_101
  - libpng=1.6.37=h1d00b33_2
  - libpq=14.1=h1ea2d34_1
  - librttopo=1.1.0=hb1df466_9
  - libsodium=1.0.18=h8d14728_1
  - libspatialite=5.0.1=hc2703d3_14
  - libssh2=1.10.0=h9a1e1f7_2
  - libtiff=4.3.0=hd413186_2
  - libwebp-base=1.2.2=h8ffe710_0
  - libxml2=2.9.12=hf5bbc77_1
  - libzip=1.8.0=h519de47_1
  - libzlib=1.2.11=h8ffe710_1013
  - lz4-c=1.9.3=h8ffe710_1
  - markupsafe=2.0.1=py38h294d835_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38h294d835_1005
  - mkl=2021.4.0=h0e2418a_729
  - mkl-service=2.4.0=py38h4f8af0f_0
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py38haa244fe_4
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.0=py38haa244fe_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - notebook=6.4.7=pyha770c72_0
  - numexpr=2.8.1=py38hb80d3ca_0
  - numpy=1.22.0=py38hcf66579_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=3.0.0=h8ffe710_2
  - os=0.1.4=0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py38h6214cd6_0
  - pandoc=2.17.0.1=h8ffe710_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pcre=8.45=h0e60522_0
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h8ffe710_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - poppler=21.11.0=h24fffdf_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.1=he353ca9_1
  - proj=8.2.1=h1cfcee9_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - pure_eval=0.2.1=pyhd8ed1ab_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyproj=3.3.0=py38hbc4243d_1
  - pyrsistent=0.18.1=py38h294d835_0
  - pysocks=1.7.1=py38haa244fe_4
  - python=3.8.12=h900ac77_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.3=pyhd8ed1ab_0
  - pywin32=303=py38h294d835_0
  - pywinpty=1.1.6=py38hd3f51b4_0
  - pyzmq=22.3.0=py38h09162b1_1
  - qutil=3.2.1=6
  - rasterio=1.2.10=py38h4cca073_4
  - requests=2.27.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.5.0=py38haa244fe_0
  - shapely=1.8.0=py38hd27d790_5
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py38haa244fe_2
  - snuggs=1.4.7=py_0
  - sqlite=3.37.0=h8ffe710_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - tbb=2021.5.0=h2d74725_0
  - terminado=0.12.1=py38haa244fe_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tiledb=2.6.1=h47404fa_0
  - tk=8.6.11=h8ffe710_1
  - tomli=1.2.2=pyhd8ed1ab_0
  - tornado=6.1=py38h294d835_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.1=py38h294d835_0
  - typing_extensions=4.0.1=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py38haa244fe_3
  - winpty=0.4.3=4
  - xerces-c=3.2.3=h0e60522_4
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.5.2=h6255e5f_0
  - pip:
    - cycler==0.11.0
    - fonttools==4.28.5
    - geopandas==0.10.2
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - matplotlib==3.5.1
    - pillow==9.0.0
    - pyspatialml==0.13
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - threadpoolctl==3.0.0
    - tqdm==4.62.3
prefix: c:\Miniconda\envs\lsm
